### ISSUE TITLE
 Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by kklepper** [pottava/docker-puppeteer#1]
What am I missing? What do I wrong?

```
docker@boot2docker:/mnt/sdd1/tmp$ docker run -it --rm -e HOST_IP -v /tmp:/tmp -v /www:/www -p 8066:3000 --name p1  pottava/puppeteer:latest  bash
puppeteer@68a410a722d2:/work$ node /home/puppeteer/index.js
(node:7) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Failed to generate minidump.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/puppeteer/lib/Launcher.js:255:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/puppeteer/lib/Launcher.js:244:50)
    at Interface.emit (events.js:185:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by pottava** [comment]
@kklepper Hi. Did you specify the binary path? You need to do.
https://github.com/pottava/docker-puppeteer/blob/master/versions/2.1/index.js#L6
And if you would like to run this with 'headless: false', you also have to specify 'args: ['--no-sandbox']'. Please take a look at my README.md, as well.

**Comment by kklepper** [comment]
Sorry, this is not an answer to my question. I provided all information I had so that you could reproduce the case.

In the meantime, I am happily working with an alternate solution.
